# -*- coding:utf-8 -*-
"""
@author Xu Guanghui
@description: Use for new frontend.
"""

_pad = '_'
_eos = '~'
_silence = 'sil'
_stop = ['ss', 'space']
_chinese = [
    'zh', 'ch', 'sh',
    'b', 'p', 'm', 'f', 'd', 't', 'n', 'l', 'g', 'k', 'h', 'j', 'q', 'x', 'r', 'z', 'c', 's', 'ng',
    'iangr0', 'iangr1', 'iangr2', 'iangr3', 'iangr4', 'iangr5',
    'uangr0', 'uangr1', 'uangr2', 'uangr3', 'uangr4', 'uangr5',
    'iongr0', 'iongr1', 'iongr2', 'iongr3', 'iongr4', 'iongr5',
    'uengr0', 'uengr1', 'uengr2', 'uengr3', 'uengr4', 'uengr5',
    'iaor0', 'iaor1', 'iaor2', 'iaor3', 'iaor4', 'iaor5',
    'uair0', 'uair1', 'uair2', 'uair3', 'uair4', 'uair5',
    'ueir0', 'ueir1', 'ueir2', 'ueir3', 'ueir4', 'ueir5',
    'uenr0', 'uenr1', 'uenr2', 'uenr3', 'uenr4', 'uenr5',
    'ianr0', 'ianr1', 'ianr2', 'ianr3', 'ianr4', 'ianr5',
    'iour0', 'iour1', 'iour2', 'iour3', 'iour4', 'iour5',
    'uanr0', 'uanr1', 'uanr2', 'uanr3', 'uanr4', 'uanr5',
    'vanr0', 'vanr1', 'vanr2', 'vanr3', 'vanr4', 'vanr5',
    'angr0', 'angr1', 'angr2', 'angr3', 'angr4', 'angr5',
    'engr0', 'engr1', 'engr2', 'engr3', 'engr4', 'engr5',
    'ingr0', 'ingr1', 'ingr2', 'ingr3', 'ingr4', 'ingr5',
    'ongr0', 'ongr1', 'ongr2', 'ongr3', 'ongr4', 'ongr5',
    'iiir0', 'iiir1', 'iiir2', 'iiir3', 'iiir4', 'iiir5',
    'air0', 'air1', 'air2', 'air3', 'air4', 'air5',
    'eir0', 'eir1', 'eir2', 'eir3', 'eir4', 'eir5',
    'aor0', 'aor1', 'aor2', 'aor3', 'aor4', 'aor5',
    'our0', 'our1', 'our2', 'our3', 'our4', 'our5',
    'ver0', 'ver1', 'ver2', 'ver3', 'ver4', 'ver5',
    'enr0', 'enr1', 'enr2', 'enr3', 'enr4', 'enr5',
    'inr0', 'inr1', 'inr2', 'inr3', 'inr4', 'inr5',
    'iar0', 'iar1', 'iar2', 'iar3', 'iar4', 'iar5',
    'uar0', 'uar1', 'uar2', 'uar3', 'uar4', 'uar5',
    'uor0', 'uor1', 'uor2', 'uor3', 'uor4', 'uor5',
    'iir0', 'iir1', 'iir2', 'iir3', 'iir4', 'iir5',
    'ar0', 'ar1', 'ar2', 'ar3', 'ar4', 'ar5',
    'or0', 'or1', 'or2', 'or3', 'or4', 'or5',
    'ir0', 'ir1', 'ir2', 'ir3', 'ir4', 'ir5',
    'ur0', 'ur1', 'ur2', 'ur3', 'ur4', 'ur5',
    'vr0', 'vr1', 'vr2', 'vr3', 'vr4', 'vr5',
    'iang0', 'iang1', 'iang2', 'iang3', 'iang4', 'iang5',
    'uang0', 'uang1', 'uang2', 'uang3', 'uang4', 'uang5',
    'iong0', 'iong1', 'iong2', 'iong3', 'iong4', 'iong5',
    'ueng0', 'ueng1', 'ueng2', 'ueng3', 'ueng4', 'ueng5',
    'iao0', 'iao1', 'iao2', 'iao3', 'iao4', 'iao5',
    'uai0', 'uai1', 'uai2', 'uai3', 'uai4', 'uai5',
    'uei0', 'uei1', 'uei2', 'uei3', 'uei4', 'uei5',
    'uen0', 'uen1', 'uen2', 'uen3', 'uen4', 'uen5',
    'ian0', 'ian1', 'ian2', 'ian3', 'ian4', 'ian5',
    'iou0', 'iou1', 'iou2', 'iou3', 'iou4', 'iou5',
    'uan0', 'uan1', 'uan2', 'uan3', 'uan4', 'uan5',
    'van0', 'van1', 'van2', 'van3', 'van4', 'van5',
    'ang0', 'ang1', 'ang2', 'ang3', 'ang4', 'ang5',
    'eng0', 'eng1', 'eng2', 'eng3', 'eng4', 'eng5',
    'ing0', 'ing1', 'ing2', 'ing3', 'ing4', 'ing5',
    'ong0', 'ong1', 'ong2', 'ong3', 'ong4', 'ong5',
    'iii0', 'iii1', 'iii2', 'iii3', 'iii4', 'iii5',
    'ai0', 'ai1', 'ai2', 'ai3', 'ai4', 'ai5',
    'ei0', 'ei1', 'ei2', 'ei3', 'ei4', 'ei5',
    'ao0', 'ao1', 'ao2', 'ao3', 'ao4', 'ao5',
    'ou0', 'ou1', 'ou2', 'ou3', 'ou4', 'ou5',
    'ie0', 'ie1', 'ie2', 'ie3', 'ie4', 'ie5',
    've0', 've1', 've2', 've3', 've4', 've5',
    'er0', 'er1', 'er2', 'er3', 'er4', 'er5',
    'an0', 'an1', 'an2', 'an3', 'an4', 'an5',
    'en0', 'en1', 'en2', 'en3', 'en4', 'en5',
    'in0', 'in1', 'in2', 'in3', 'in4', 'in5',
    'vn0', 'vn1', 'vn2', 'vn3', 'vn4', 'vn5',
    'ia0', 'ia1', 'ia2', 'ia3', 'ia4', 'ia5',
    'ua0', 'ua1', 'ua2', 'ua3', 'ua4', 'ua5',
    'uo0', 'uo1', 'uo2', 'uo3', 'uo4', 'uo5',
    'ii0', 'ii1', 'ii2', 'ii3', 'ii4', 'ii5',
    'a0', 'a1', 'a2', 'a3', 'a4', 'a5',
    'o0', 'o1', 'o2', 'o3', 'o4', 'o5',
    'e0', 'e1', 'e2', 'e3', 'e4', 'e5',
    'i0', 'i1', 'i2', 'i3', 'i4', 'i5',
    'u0', 'u1', 'u2', 'u3', 'u4', 'u5',
    'v0', 'v1', 'v2', 'v3', 'v4', 'v5',
]

_english = ['AA', 'AE', 'AH', 'AO', 'AW', 'AX', 'AXR', 'AY', 'B', 'CH', 'D', 'DH', 'EH', 'EL', 'EM',
            'EN', 'ER', 'EY', 'F', 'G', 'HH', 'HV', 'IH', 'IX', 'IY', 'JH', 'K', 'L', 'M', 'N', 'NG',
            'NX', 'OW', 'OY', 'P', 'R', 'S', 'SH', 'T', 'TH', 'UH', 'UW', 'V', 'W', 'X', 'Y', 'Z', 'ZH']

symbols = [_pad, _eos, _silence] + _stop + _chinese + _english
